// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnCZlDbVTGk0TqJbRtmLLs2fWtH7YaeZ8',
    appId: '1:283199328375:web:b5346a9a77c7febac4f672',
    messagingSenderId: '283199328375',
    projectId: 'expirydatealert',
    authDomain: 'expirydatealert.firebaseapp.com',
    storageBucket: 'expirydatealert.appspot.com',
    measurementId: 'G-6TQ0V12S0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUmRo1qCujQsE7EsPnxP2uT6rT0PIF14',
    appId: '1:283199328375:android:bdb1ec09bc9f6c73c4f672',
    messagingSenderId: '283199328375',
    projectId: 'expirydatealert',
    storageBucket: 'expirydatealert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTLhP9H7vTIQ94jb88e-da9msD1uR2zbI',
    appId: '1:283199328375:ios:9d8e8f67c3f15cb0c4f672',
    messagingSenderId: '283199328375',
    projectId: 'expirydatealert',
    storageBucket: 'expirydatealert.appspot.com',
    iosClientId: '283199328375-n3gor6a01k67o5qt1r9esq87had0nkru.apps.googleusercontent.com',
    iosBundleId: 'com.example.expirydatefyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTLhP9H7vTIQ94jb88e-da9msD1uR2zbI',
    appId: '1:283199328375:ios:9d8e8f67c3f15cb0c4f672',
    messagingSenderId: '283199328375',
    projectId: 'expirydatealert',
    storageBucket: 'expirydatealert.appspot.com',
    iosClientId: '283199328375-n3gor6a01k67o5qt1r9esq87had0nkru.apps.googleusercontent.com',
    iosBundleId: 'com.example.expirydatefyp',
  );
}
